name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up environment variables
      run: |
        # Backend environment
        echo "DATABASE_URL=postgres://testuser:testpass@localhost:5432/testdb" > backend/.env
        echo "JWT_SECRET=test-secret" >> backend/.env
        echo "SEED_USER_USERNAME=test" >> backend/.env
        echo "SEED_USER_PASSWORD=password" >> backend/.env
        echo "SEED_USER_EMAIL=test@test.com" >> backend/.env
        
        # Frontend environment (using localhost since we're running everything in the same workflow)
        echo "VITE_API_URL=http://localhost:4000" > frontend/.env

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci
        cd ../tests && npm ci

    - name: Start Backend
      working-directory: ./backend
      run: |
        npm run migrate
        npm start &
        sleep 5  # Give backend time to start

    - name: Start Frontend
      working-directory: ./frontend
      run: |
        npm run build
        npm run preview -- --port 3000 &
        sleep 5  # Give frontend time to start

    - name: Run Cypress Tests
      working-directory: ./tests
      run: |
        npm run test:ui

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: |
          tests/screenshots/
          tests/videos/
        retention-days: 7
